### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by seolhokim** [syuntoku14/pytorch-rl-il#5]
# In python 3.6 version
## **setting**
conda 4.8.5
```
conda create -n test python = 3.6
conda activate test
pip install -e .
conda install pytorch torchvision torchaudio cpuonly -c pytorch
conda install -c conda-forge tensorboard
```
## **run**
`
python scripts/continuous/online.py ant ppo --train_minutes 60 --num_workers 5 --exp_info example_training
`

`
Traceback (most recent call last):
  File "scripts/continuous/online.py", line 5, in <module>
    from rlil.experiments import Experiment
  File "/home/tactics/KimMin/test/pytorch-rl-il/rlil/experiments/__init__.py", line1, in <module>
    from .experiment import Experiment
  File "/home/tactics/KimMin/test/pytorch-rl-il/rlil/experiments/experiment.py", line 4, in <module>
    from rlil.samplers import AsyncSampler
  File "/home/tactics/KimMin/test/pytorch-rl-il/rlil/samplers/__init__.py", line 2,in <module>
    from rlil.samplers.asyncsampler import AsyncSampler, StartInfo
  File "/home/tactics/KimMin/test/pytorch-rl-il/rlil/samplers/asyncsampler.py", line 15, in <module>
    defaults=(None, ) * 3)
TypeError: namedtuple() got an unexpected keyword argument 'defaults'
`
# In python 3.7 version
## **setting**
conda 4.8.5
```
conda create -n test python = 3.7
conda activate test
pip install -e .
conda install pytorch torchvision torchaudio cpuonly -c pytorch
conda install -c conda-forge tensorboard
```
## **run**
`
python scripts/continuous/online.py ant ppo --train_minutes 60 --num_workers 5 --exp_info example_training
`

`
Traceback (most recent call last):
  File "scripts/continuous/online.py", line 69, in <module>
    main()
  File "scripts/continuous/online.py", line 34, in main
    ray.init(include_webui=False, ignore_reinit_error=True)
  File "/home/tactics/anaconda3/envs/test/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
TypeError: init() got an unexpected keyword argument 'include_webui'
`
what can i do?

**Comment by chenxi-yang** [comment]
Did you solve this problem? Thanks

**Comment by seolhokim** [comment]
@cxyang1997 No I didnt

**Comment by chenxi-yang** [comment]
ok, thanks! I delete the include_webui=False in the code, then it works.

**Comment by seolhokim** [comment]
@cxyang1997 Thank you so much! I'll try again next time :)
